# Generated by Django 5.0 on 2023-12-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50, unique=True)),
                ('course_title', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=30)),
                ('open_seats', models.IntegerField(default=30)),
            ],
        ),
    ]
